apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: guestbook-ui  # Name of the container in your Deployment
    newName: dewandemo/guestbook-dev
    newTag: "0.1"
