apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: prod-config
    files:
      - config.json
patchesStrategicMerge:
  - patch-deployment.yaml
